//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicios_Algoritmos_Basicos {
	
	
	public partial class imc {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.HtmlControls.HtmlForm form;
		
		protected System.Web.UI.WebControls.TextBox txtWeight;
		
		protected System.Web.UI.WebControls.TextBox txtHeight;
		
		protected System.Web.UI.WebControls.Button btnSend;
		
		protected System.Web.UI.WebControls.Button btnClear;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl result;
	}
}
